### ISSUE TITLE
Long press on playlist has no effect

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#47]
**The Issue**
A long press on any playlist in the library has no effect.

**To Reproduce**
1. Navigate to Library.
2. Long press on any playlist.
3. Note there is no effect.

**Expected behavior**
Long press on any playlist in the library should result in popup menu and share link.

**Device**
 - iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.9.0 (171)

**Comment by KCreek1** [comment]
Given the success I had scrolling on iPad with Bluetooth mouse I thought I'd go back and try something with this. 

Using right click on mouse I was able to bring up the pop up (share) menu for tracks. 

iPad 7th gen
iPad is 16.7
Weezify 1.9.0 (173)

**Comment by KCreek1** [comment]
This issue seems to be related to issue #14 and partially issue #7 in that this function works when using a mouse and not touch in iPad app and iPad web.

**Comment by KCreek1** [comment]
I just tried this on Chromebook browser with touch screen. Same results. 

Maybe for this action touch is not listed as a pointer device kind?

**Comment by riverscuomo** [comment]
something in TappablePlaylistWidget

i hope i didn't screw up onSecondaryTapUp: (details) => contextMenuBehavior,

**Comment by riverscuomo** [comment]
// The problem is that both `TapUpDetails` and `LongPressEndDetails` classes 
//do not inherit from the same superclass, so it's not possible to just use 
//a superclass type for the `details` parameter. 

// A solution could be to define two separate methods for `createWeezifyContextMenuBehavior`. 
//Each one dedicated to a specific details type.

weezifymenus.dart

**Comment by SlightlyCompletely** [comment]
Resolved in Weezify 1.12.0 (186) on iPad Air running iPadOS 17.0.3.
