### ISSUE TITLE
iPad can’t drag/drop to resequence playlists

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#91]
**The bug**
Previously a press on a lefthand playlist would allow drag and drop resequencing. Now the press results in a menu but doesn’t allow any drag/drop capability.

**To Reproduce**
1. In lefthand library, press a playlist name and try to move up or down.
2. Note that a menu appears with a long press or scrolling is possible with shorter press/swipe, but no drag/drop movement occurs.

**Expected behavior**
There should be drag and drop resequencing of playlists, but long press leads to menu instead.

**Device:**
 - iPad Air 5th gen
 - OS: iPadOS 17.0.3
 - Weezify 1.12.0 (186)

**Comment by riverscuomo** [comment]
I got access to an old iPad so I should be able to examine these issues a little more successfully.

I'm trying to replicate the functionality of Spotify. In this case as far as I can tell long pressing a playlist on Spotify opens a menu rather than initiates a drag and drop procedure. If I'm misunderstanding, please feel free to reopen this issue with more information.
